# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Benjamin Ekow Attabra
title: KNUST Undergraduate Student
email: beattabra@st.knust.edu.gh
email_title: E-mail
website: attabeezy.github.io
website_title: portfolio website

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: benattabra
github_username:  attabeezy
stackoverflow_username: "27450700"
# dribbble_username: jekyll
# flickr_username: jekyll
# instagram_username: attabeezy
linkedin_username: ben-attabra
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009-0008-6963-5422

# Additional icon links
additional_links:
- title: resume
  icon: fas fa-file
  url: https://drive.google.com/file/d/1rRHjJKIp8S7W0K6S4TCzny-BwqzuJqG5/view?usp=drive_link

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am an undergraduate at the Kwame Nkrumah University of Science and Technology studying [Telecom Engineering](https://teleng.knust.edu.gh/) in the [Faculty of Electrical and Computer Engineering](https://coe.knust.edu.gh/faculties/faculty-electrical-computer-engineering) under the mentorship of [Dr. Francisca Adoma Acheampong](https://webapps.knust.edu.gh/staff/dirsearch/profile/summary/fb34c7d09958.html). 
  
  I have interests in Machine Learning and Quant Finance, focusing on the application of machine learning techniques for problem-solving. Furthermore, I have experience in applying mathematical modeling to predict market capitalization and identify arbitrage betting opportunities. [ResearchGate](https://www.researchgate.net/profile/Benjamin-Attabra/research)

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        border: weak
        title: Sequential Deep Learning for Credit Risk Modelling
        link_text: https://github.com/Attabeezy/sequential-crm-for-dce
        quote: >
          Cause if you ain't doing what you love it's only you to blame
        description: | # this will include new lines to allow paragraphs
          Developing a Sequential Deep Learning framework for Credit Risk Modelling in data-constrained emerging markets. Leveraging Recurrent Neural Networks (RNNs), the model captures temporal dependencies in fragmented financial history data to significantly improve prediction accuracy over traditional methods.
      - layout: top-middle
        border: weak
        title: "SWELM: Semantic Weighting for Equitable Language Modeling"
        link_text: https://github.com/Attabeezy/semweight-equity
        quote: >
          Call my unborn son and tell him that's the mission
        description: |
          Addressing equitable performance in multilingual NLP models (compatible with Llama 3, GPT). Designed and applied a novel Semantic Weighting and Adaptive Sampling strategy to dynamically adjust training distributions based on language representation quality.
      - layout: top-middle
        border: weak
        title: Quant Enthusiasts Risk Engine
        link_text: https://github.com/Attabeezy/Quant-Enthusiasts-Risk-Engine
        quote: >
          Found my position, let's hit the road
        description: |
          Contributed to a comprehensive quantitative risk engine in Python designed for calculating and simulating key financial risk metrics. The engine supports multiple estimation methods for Value-at-Risk (VaR) and Conditional Value-at-Risk (CVaR). Implemented Monte Carlo simulation capabilities to conduct portfolio stress testing and provide robust risk management analysis for various asset classes.

  - title: Papers # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: "2023"
        description: |
            **Benjamin Ekow Attabra** (2023). [Market Capitalization Forecasting with Annuity Due Models](https://www.researchgate.net/publication/387671507_Market_Capitalization_Forecasting_with_Annuity_Due_Models). This paper presents a mathematical model for estimating the future market capitalization of public companies by adapting the future value of annuity due formula. Using principles from geometric series and compound interest, we demonstrate how this model can provide structured forecasts for company valuations, providing a systematic approach based on established financial mathematics principles.

      - layout: left
        title: ""
        description: |
            **Benjamin Ekow Attabra** (2023). [Mathematical Analysis of Multi-Outcome Sports Betting Arbitrage: A System of Equations Approach](https://www.researchgate.net/publication/387671984_Mathematical_Analysis_of_Multi-Outcome_Sports_Betting_Arbitrage_A_System_of_Equations_Approach). This paper introduces a mathematical framework for identifying arbitrage opportunities in three-outcome sports betting markets. By utilizing systems of simultaneous equations, we develop a method for optimal stake allocation across bookmakers.

  - title: Experience
    layout: text
    content: |
        [Quantitative Research, Forage (JPMorgan Chase & Co), Virtual Experience - October 2024](https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/J.P.%20Morgan/bWqaecPDbYAwSDqJy_JPMorgan%20Chase%20&%20Co._BiFrcQzs4S9huhHGM_1728733265196_completion_certificate.pdf)
        - Completed a simulation focused on quantitative research methods
        - Analyzed a book of loans to estimate a customer's probability of default
        - Used dynamic programming to convert FICO scores into categorical data to predict defaults

        [Data Analytics Intern, Forage (Quantium), Virtual Experience - March 2025](https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/32A6DqtsbF7LbKdcq/NkaC7knWtjSbi6aYv_32A6DqtsbF7LbKdcq_BiFrcQzs4S9huhHGM_1743333311609_completion_certificate.pdf)
        - Utilized transaction datasets to extract valuable insights and deliver data-driven commercial recommendations
        - Identified benchmark stores for conducting uplift testing on trial store layouts, enabling evidence-based decision-making
        - Create comprehensive reports for the Category Manager, facilitating informed strategic decisions and enhancing commercial applications.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
